create table t1
(
    i1  int DEFAULT (`a`),
    i2  int DEFAULT (`a` IS NULL),
    i3  int DEFAULT (`a` IS NOT NULL),
    i4  int DEFAULT (a IS TRUE),
    i5  int DEFAULT (a IS NOT TRUE),
    i6  int DEFAULT (a IS FALSE),
    i7  int DEFAULT (a IS NOT FALSE),
    i8  int DEFAULT (a BETWEEN b AND c),
    i9  int DEFAULT (a NOT BETWEEN b AND c),
    i10 int DEFAULT (CASE a WHEN 1 THEN 2 END),
    i11 int DEFAULT (CASE `a` WHEN 1 THEN 2 WHEN 2 THEN 3 END),
    i12 int DEFAULT ('a' != 1),
    i13 int DEFAULT ('a' = 1),
    i14 int DEFAULT (3 < 5),
    i15 int DEFAULT (10 > 5),
    i16 int DEFAULT (3 + 5),
    i17 int DEFAULT (3 - 5),
    i18 int DEFAULT (3 <> 5),
    i19 int DEFAULT ((1 + 2) * 3),
    i20 int DEFAULT (1 + 2 * 3),
    i21 int DEFAULT (default(i)),
    i22 int DEFAULT ('a' IN ('b')),
    i23 int DEFAULT (2 in (0, 3, 7)),
    i24 int DEFAULT (2 not in (0, 3, 7)),
    i25 int DEFAULT (a sounds like 't1'),
    i27 int DEFAULT (a like 't1'),
    i28 int DEFAULT (a not like 't1'),
    i29 int DEFAULT (a regexp '^[a-zA-Z][0-9]{11}|ok$'),
    i30 int DEFAULT (a not regexp '^[a-zA-Z][0-9]{11}|ok$'),
    i31 int DEFAULT ((0, 3, 7)),
    i32 int DEFAULT (ROW (`a`, `b`)),
    i33 int DEFAULT ({`a` 1}),
    i34 int DEFAULT (MATCH (`a`) AGAINST ('abc')),
    i35 int DEFAULT (MATCH (`a`) AGAINST ('abc' IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION)),
    i36 int DEFAULT (@a > 1),
    i37 int DEFAULT (@`a` + 1),
    i38 int DEFAULT (@a = 2),
    i39 int DEFAULT (@@aa),
    i40 int DEFAULT (@@`aa`),
    i41 int DEFAULT (@@`GLOBAL.aa`),
    i42 int DEFAULT (@@`SESSION.aa`)
);