project_name: alternator
before:
  hooks:
    - make clean yacc
builds:
  - main: .
    binary: alternator
    ldflags:
      - -s -w
      - -X github.com/kota65535/alternator/cmd.Version={{.Version}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto