project_name: alternator
before:
  hooks:
    - make clean yacc
builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/kota65535/alternator/cmd.version={{.Version}}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: alternator
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
brews:
  - tap:
      owner: kota65535
      name: homebrew-alternator
    folder: Formula
    homepage: https://github.com/kota65535/alternator
    description: alternator
