create database db1;

CREATE DATABASE IF NOT EXISTS `db2`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_bin
    DEFAULT ENCRYPTION 'Y';

CREATE DATABASE IF NOT EXISTS `db3`
    DEFAULT CHARACTER SET = utf8mb4
    DEFAULT COLLATE = utf8mb4_bin
    DEFAULT ENCRYPTION = 'Y'
