CREATE TABLE `t3`
(
    `int1` int,
    `int2` int,
    CONSTRAINT `u1` PRIMARY KEY (`int1`, `int2`) USING BTREE KEY_BLOCK_SIZE 1 COMMENT 'foo' VISIBLE,
    CONSTRAINT `u2` UNIQUE KEY (`int1`, `int2`) USING BTREE KEY_BLOCK_SIZE 1 COMMENT 'foo' VISIBLE,
    CONSTRAINT `u3` FOREIGN KEY `i3` (`int1`, `int2`) REFERENCES `t1` (`int1`, `int2`) MATCH FULL ON DELETE RESTRICT ON UPDATE CASCADE
);