CREATE TABLE `t1`
(
    `char1`       char,
    `char2`       char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin        NOT NULL DEFAULT 'a',
    `varchar1`    varchar(1),
    `varchar2`    varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin     NOT NULL DEFAULT 'a',
    `binary1`     binary,
    `binary2`     binary(1)                                                NOT NULL DEFAULT 'a',
    `varbinary1`  varbinary(1),
    `varbinary2`  varbinary(2)                                             NOT NULL DEFAULT 'a',
    `tinyblob1`   tinyblob,
    `tinyblob2`   tinyblob                                                 NOT NULL,
    `tinytext1`   tinytext,
    `tinytext2`   tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin       NOT NULL,
    `blob1`       blob,
    `blob2`       blob(1)                                                  NOT NULL,
    `text1`       text,
    `text2`       text(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin        NOT NULL,
    `mediumblob1` mediumblob,
    `mediumblob2` mediumblob                                               NOT NULL,
    `mediumtext1` mediumtext,
    `mediumtext2` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin     NOT NULL,
    `longblob1`   longblob,
    `longblob2`   longblob                                                 NOT NULL,
    `longtext1`   longtext,
    `longtext2`   longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin       NOT NULL,
    `enum1`       enum('a'),
    `enum2`       enum('a', 'b') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'a',
    `set1`        set('a'),
    `set2`        set('a', 'b') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin  NOT NULL DEFAULT 'a'
);