name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get tool versions
        uses: kota65535/github-asdf-parse-action@v1
        id: versions
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.versions.outputs.golang }}
      - name: Install goyacc
        run: go install golang.org/x/tools/cmd/goyacc@latest
      - name: Run test
        run: make clean test
